### PR TITLE
Add humanize helper, updated DescriptionList to use it

### PR DESCRIPTION
**Pull request by 401matthall**
Borrowed the humanize function from Phoenix.Naming module. It's
one of those situations where once you've seen the solution it's
pretty difficult to build anything else.

### CODE REVIEW

**Review by adkron — APPROVED** [review]
@401matthall, I know you talked in slack about handling humanize. What if we made it configurable and you could pick the lilly humanizer?

**Comment by adkron** [comment]
Good work. That is a great improvement.

**Comment by 401matthall** [comment]
> @401matthall, I know you talked in slack about handling humanize. What if we made it configurable and you could pick the lilly humanizer?

I guess it depends on how complex you can envision a `humanize` function. I can see where we could make the humanize function a prop of the component and have it use the one set in config by default but that feels like an awful lot without my having a better understanding of what you might be envisioning.

Share with me your vision, @adkron!

**Comment by adkron** [comment]
People often want to have different rules for how to humanize things. Some want multiple words to have up-cased. Some people want only the first word upper. There are a lot of different ways. If you could pass that function in an application config it might be better. Also, this code assumes Ecto with the id part but what if I have id as part of my actually thing. government_id.

**Comment by 401matthall** [comment]
M'kay, I'ma push a button here. Let me say, I am not opposed to being told to add the ability to do this but if we're having a buy-in conversation I'm not quite convinced yet. Let me ask the question directly for clarity: Are you _telling_ me to add this functionality? Are you _voting_ for this functionality? What conversation are we having? :sweat_smile:

**Comment by adkron** [comment]
Since we have the label I don’t care at the moment. If im ever telling you something is a must do I will try to be very clear about that. 

Amos King
CEO
Binary Noggin

**Pull request merged**
